#!/Users/user/PythonProjects/Numerolog_professional/.venv/bin/python3.13
from loguru import logger
from pathlib import Path
import os


from business_logic.arcanes_classes import Client, Star, Triangle
from business_logic.analytic_class import MoneyAnalyticInfo

from input_module.clients_info import get_client_info
from data_requests.data_combiner import combine_all_data
from data_requests.fullstar_data import get_fullstar_data
from reports.pdf_creator import create_numerology_report


# Основная функция программы
@logger.catch
def main():
    """
    Главная функция программы. Выполняет следующие шаги:
    1. Получение данных клиента.
    2. Создание арканов для полной звезды FullStar по данным клиента
       и подготовка данных для создания страницы FullStar.
    3. Объединение данных для создания страниц с настройками
       (шрифтами, координатами).
    4. Создание отчета в виде pdf файла.
    """
    # Настройка логгера
    # configure_logger()

    # 1. Получение данных клиента
    logger.info("Получение данных клиента...")
    client_info = get_client_info()
    # client_info = get_client_info(('Julia', '23.07.1982'))

    logger.debug(f'Имя и ДР клиента {client_info}')

    # 2. Создание арканов для FullStar по данным клиента.
    # и подготовка данных для создания страницы FullStar.
    logger.info("Создание контента страницы ТД")
    star = Star(client_info=client_info)

    page_fullstar_content = get_fullstar_data(star=star)
    logger.debug(f'FullStar: {page_fullstar_content}')

    # 3. Объединение данных для создания страниц с настройками
    logger.info("Объединение данных для итогового отчета...")
    page_fullstar_analytic = []
    union_fullstar_data = combine_all_data(
        page_fullstar_content, page_fullstar_analytic,
        page_name='fullstar'
    )
    logger.debug(f'Объединенные данные {union_fullstar_data}')
    logger.info("Объединение данных завершено")

    # 4. Создание отчета в виде pdf файла.
    result = create_numerology_report(union_fullstar_data, pointer='fullstar')
    logger.info("Завершение создания страницы FullStar")
    # Завершение создания страницы FullStar

    # Завершение работы программы
    logger.info("Программа успешно завершила работу.")


# Точка входа в программу
if __name__ == "__main__":
    from utils.log_utils import configure_logger
    configure_logger()
    main()
