#!/Users/user/PythonProjects/Numerolog_professional/.venv/bin/python3.13
from loguru import logger
from pathlib import Path
import os

from business_logic.arcanes_classes import Client, Star, Triangle
from business_logic.analytic_class import MoneyAnalyticInfo

from input_module.package_info import get_client_info
from data_requests.data_combiner import combine_all_data
from reports.pdf_creator import create_star_report, create_money_report

from statistic_service.clients_bd import clients_list

# Основная функция программы


@logger.catch
def main():
    """
    Главная функция программы. Выполняет следующие шаги:
    1. Получение данных клиента.
    2. Создание арканов для треугольника денег (ТД) по данным клиента.
    3. Подготовка данных для создания страницы ТД.
    4. Подготовка данных для создания страниц аналитики ТД.
    5. Объединение данных для создания страниц с настройками
       (шрифтами, координатами).
    6. Создание отчета в виде pdf файла.
    """
    # Настройка логгера
    # configure_logger()

    # 1. Получение данных клиента
    clients_list = [('Наталья Воротникова', '10.04.1976'),
                    ('Зулия Раджабова', '30.11.1985'),
                    ('Мехди Эбрагими', '8.06.1973'),
                    ('Лилия Хегай', '4.07.1965'),
                    ('Александр Литвин', '25.07.1960'),
                    ('Алексей Похабов', '28.11.1983'),
                    ('Владимир Муранов', '19.02.1974'),
                    ('Наталья Бантеева', '16.02.1975'),
                    ('Мохсен Норузи', '31.01.1960'),
                    ('Виталий гиберт', '21.03.1988'),
                    ('Елена Ясевич', '12.12.1978'),
                    ('Дмитрий Волхов', '27.10.1988'),
                    ('Александр Шепс', '26.11.1986'),
                    ('Виктория Райдос', '27.12.1976'),
                    ('Свами Даши', '22.8.1967'),
                    ('Константин Гецати', '7.7.1987'),
                    ('Тимофей Руденко', '19.03.1990'),
                    ('Дмитрий Матвеев', '15.07.1997'),
                    ('Олег Шепс', '29.04.1998'),
                    ('Максим Левин', '9.09.1978'),
                    ('Владислав Череватый', '28.7.1996'),
                    ('Артем краснов', '28.08.1998'),
                    ('Снежана', '4.2.1981'),
                    ('Алина', '15.10.1982'),
                    ('Виктория', '26.10.1989'),
                    ('Джулия', '19.10.1981'),
                    ('Свами Даши', '22.08.1967')
                    ]

    for client in clients_list:
        client_info = get_client_info(client)

        # 2. Создание арканов для ТД по данным клиента.
        client_star = Star(client_info)
        client_money = Triangle(client_star)

        # 3. Подготовка данных для создания страницы ТД.
        page_star_content = client_star.get_all_content()
        page_money_content = client_money.get_all_content()

        # 4. Подготовка данных для создания страниц ТД.
        page_star_analytic = ''

        page_money_analytic = ''

        # 5. Объединение данных для создания страниц с настройками
        union_star_data = combine_all_data(
            page_star_content, page_star_analytic,
            page_name='star'
        )

        union_money_data = combine_all_data(
            page_money_content, page_money_analytic,
            page_name='money'
        )

        # 6. Создание отчета в виде pdf файла.
        result = create_star_report(union_star_data)
        result = create_money_report(union_money_data)
        # Завершение создания страницы star

        # Завершение работы программы
        logger.info("Программа успешно завершила работу.")

        # Точка входа в программу
if __name__ == "__main__":
    from utils.log_utils import configure_logger
    configure_logger()
    main()
